:caps:
  :platformName: "iOS"
  :bundleId: "com.experitest.ExperiBank"
  :deviceName: "Test Automation"
  :app: ""
  :noReset: false
  :fullReset: false
  :automationName: "XCUITest"
  :autoWebView: true
  :setWebContentsDebuggingEnabled: true
  :autoAcceptAlerts: true
  :autoGrantPermissions: true
  :newCommandTimeout: 600
  :appiumVersion: 1.22.2

:appium_lib:
    :server_url: "http://127.0.0.1:4723/wd/hub"
